apiVersion: batch/v1
kind: Job
metadata:
  name: my-pyspark-job
spec:
  template:
    spec:
      containers:
        - name: kampret
          image: 637423199605.dkr.ecr.eu-north-1.amazonaws.com/kampret:latest
      restartPolicy: Never
  backoffLimit: 4
