---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 637423199605.dkr.ecr.eu-north-1.amazonaws.com/kampret:latest
          ports:
            - containerPort: 8080

